export const fetchActionTypes = {
  FETCH_USER: "FETCH_USER",
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_WHOLE_USER: "FETCH_WHOLE_USER",

  SET_CURRENT_USER: "SET_CURRENT_USER", //로그인시
  CLEAR_CURRENT_USER: "CLEAR_CURRENT_USER", //로그아웃시

  ADD_WISHED_PRODUCT: "ADD_WISHED_PRODUCT", //찜하기
  REMOVE_WISHED_PRODUCT: "REMOVE_WISHED_PRODUCT", //찜취소

  MODIFY_PROFILE: "MODIFY_PROFILE", //프로필사진 수정

  ADD_COMMENTS: "ADD_COMMENTS",
};
