export const fetchActionTypes = {
  FETCH_USER: "FETCH_USER",
  FETCH_WHOLE_USER: "FETCH_WHOLE_USER",
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  ADD_PRODUCT: "ADD_PRODUCT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
};
